name: Tag Merge to Master

on:
  push:
    branches:
    - master

env:
  CGO_ENABLED: "0"

jobs:

  tag:
    name: Bump semantic version
    runs-on: [ubuntu-latest]
    steps:

    - uses: actions/checkout@v2

    - uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        WITH_V: true

  build:
    name: Build
    needs: [tag]
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-go@v1
      with:
        go-version: 1.13.x

    - uses: actions/checkout@v2

    # Because the GITHUB_REF will be refs/heads/master,
    # We need to get the tag for the current commit
    # git describe --tags
    - name: Get the version
      id: tag
      shell: bash
      run: |
        git pull
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        echo ::set-output name=result::$(git describe --tags)

    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - shell: bash
      env:
        OS: ${{ runner.os }}
        TAG: ${{ steps.tag.outputs.result }}
      run: |
        go build -o terraform-provider-infoblox_${TAG} -mod=vendor
        mkdir build
        zip build/terraform-provider-infoblox.zip terraform-provider-infoblox_${TAG}

    - uses: actions/upload-artifact@v1
      with:
        name: build
        path: build

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:

    - uses: actions/checkout@v2

    # Because the GITHUB_REF will be refs/heads/master,
    # We need to get the tag for the current commit
    # git describe --tags

    - name: Get the version
      id: tag
      shell: bash
      run: |
        git pull
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        echo ::set-output name=result::$(git describe --tags)

    - uses: actions/download-artifact@v1
      with:
        name: build
        path: build

    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag.outputs.result }}
        draft: true
        prerelease: true
        artifacts: "build/*" # Output path of Go build from the Merge Master workflow
        body: |
          # Release ${{ steps.tag.outputs.result }}
          
          ## Features
          - here
          
          ## Fixes
          - here
        token: ${{ secrets.GITHUB_TOKEN }}
